import BooksIssuedInRange from './bookissuedingiventime';
import BookIssuers from './bookissuers';
import BooksIssuedByUser from './booksissuedbyuser';
import RentGeneratedByBook from './rentgeneretedbybook';
import { useState } from 'react';
import { Container, Form } from 'react-bootstrap';

export default function Select(){
    const [filterType, setFilterType] = useState('');
    
    const handleFilterTypeChange = (e) => {
        setFilterType(e.target.value);
    };
    return(
            <Container className="mt-4">
            <h1>Filter Transaction</h1>

            <Form.Group className="mb-3">
                <Form.Label>Select Transaction Filter Type</Form.Label>
                <Form.Control as="select" value={filterType} onChange={handleFilterTypeChange}>
                    <option value="">--Select--</option>
                    <option value="bookissuedingiventime">Filter Transactions by Date</option>
                    <option value="bookissuers">Filter For Get List Of Bookissuers</option>
                    <option value="booksissuedbyuser">Filter For Get List of Users of book</option>
                    <option value="rentgenerated">Filter For get Rent Generated by book</option>
                </Form.Control>
            </Form.Group>

                {filterType === 'bookissuedingiventime' && (
                    <BooksIssuedInRange/>
                )}

                {filterType === 'bookissuers' && (
                    <BookIssuers/>
                )}

                {filterType === 'booksissuedbyuser' && (
                    <BooksIssuedByUser/>
                )}

                {filterType === 'rentgenerated' && (
                    <RentGeneratedByBook/>
                )}

        </Container>
    );
}